
HR = {
    "def programa"              : "- Post processor 3-aksijalne obare tokarenjem za CATIA APT file u WinNC G-kod \n -SVI PODACI O NOŽEVIMA MORAJU BITI ISTI U OBA PROGRAMA \n- Za urezivanje navoja, potrebno je definirati operaciju kao Cycle \n- Pod naredbom FEEDRAT ne smije biti naredba RAPTO \n- Nema definiranja linija ili točaka \n- Nema pomaka do točke, linje ili površine \n- Nema makro rutina \n- Nema definiranja varijabli \n- Nema grananja u programu\n- Nema logičkih uvjeta",
    "Nije predana datoteka."    : "Nije predana datoteka. ",
    "Nepostojeća datoteka."     : "Nepostojeća datoteka. ",
    "Neispravna vrsta"          : "Neispravna vrsta datoteke (potrebno je .txt). ",
    "Datoteka učitana:"         : "- Datoteka učitana: ",
    "Učitavanje linija"         : "- Učitavanje linija ",
    "error"                     : "Greška prilikom čitanja datoteke: ",
    "Gotovo."                   : "M30\n- Gotovo. ",
    "Nepoznata naredba"         : "Greška - provjeriti naredbu (nije u niti jednoj kategoriji naredbe): ",
    "catia komentari"           : "- Želite li zadržati komentare iz CATIA APT datoteke? (DA/NE): ",
    "kriv odabir da/ne"       : "- Neispravan odabir. Unesite ponovo. (DA/NE).",
    "cta crc cent nije isti"    : "Greška - centri luka se ne poklapaju: ",
    "sredina na tang"           : "Greška - Sredina luka na tangeni: ",
    "nepoznata ravnina"         : "Greška - ravnina nepravilno zapamćena nije (G17, G18 ili G19): ",
    "promjena 3x koord"         : "Greška - promjena 3 koordinate u jednoj liniji: ",
    "nepoznat posmak"           : "- Provjeriti način posmaka (sfm ili rpm): ",
    "coolant on off flood mist" : "- Provjeriti slijedeću liniju i unijeti vrijednost (ON/OFF/FLOOD/MIST): ",
    "coolant on off"            : "- Unesite ON ili OFF: ",
    "spindle m3/m4"             : "- Provjeriti i unijeti vrijednost smjera vrtnje (CCLW/CLW/OFF): ",
    "holder type"               : "- Definirajte vrstu držača ureznice: pomični (Upišite 0) ili fiksni (Upišite 1): ",
    "nepoznat posmak"           : "- Provjeriti način posmaka (RPM ili SFM): ",
    ";Krivi broj"               : "- Krivi broj...",
    "feedrat err"               : "- Provjeriti u unijeti ispravnu feedrate vrijednost (Treba pisati MMPR ili MMPM): ",
    "posmak"                    : "- Unesite RPM ili SFM: ",
    "circle feed"               : "- Unesite brzinu posmaka za kružne pokrete za grubu i finu obradu, (način posmaka): ",
    "magazine slot"             : ";Pozicija na magazinu broj ",
    "insert r"                  : ";Radijus oštrice: ",
    "spindle start"             : "- Prilikom pokretanja vretena iz M05 u M03/M04, trebali ponovo ispisivati okretaje / brzinu rezanja i smjer vrtnje ne? (DA/NE): ",
    "krivi spindle start"       : "- Neispravan odabir unesite ponovo",
    "ls-clnt"                   : "- Odabrite način podmazivanja (FLOOD/MIST): ",
    "neispravan godlta"         : "Greška - neispravan golta value: ",
    "intol"                     : ";Unutarna tolerancija putanje: ",
    "outtol"                    : ";Vanjska tolerancija putanje: ",
    "toler"                     : ";Tolerancija putanje: ",
    "Nema ciklusa"              : "Greška - Nema definiranog ciklusa: ",
    "unijeti ravninu - kruznica": "- Greška - Nije definirana ravnina obrade kružnog luka. Unesite (G17, G18 ili G19): ",
    "units"                     : "- Unesite vrstu mjernih jedinica (MM/INCH):",
    "neispravni podaci"         : "Greška - neispravni podaci za naredbu:",
    "spremljeno u"              : "Datoteka je prevedena i spremljena u: ",
    "partno"                    : ";Dio: ",
    "unesite datoteku"          : "- Unesite naziv datoteke (.txt datoteka s ): ",
    "tlaxis"                    : "; Sljedeće vrijednosti su mogući smjerovi vektora rezanja oštricom:",
    "neobradeni cycle"          : "Greška - neobrađena cCycle komanda: ",
    "pokretanje"                : "Pokretanje Post procesora...\n",
    "naziv output fl"           : "Unesite naziv izlazne datoteke: ",
    "ekstenzija output"         : "Unesite ekstenziju izlazne datoteke (stisnite ENTER za .txt): ",
    "save file y/n"             : "Želite li stvoriti izlaznu datoteku? (DA/NE): ",
    "neispravni naziv"          : "Greška - neispravan naziv datoteke.",
    "kraj"                      : "Kraj programa.",
    "ne zeli spremiti"          : "G-code je ispisan u terminalu."

}

EN = {
    "def programa"              : "- Post processor for 3-axis lathe for CATIA APT file to WinNC G-code \n- ALL TOOL DATA MUST BE THE SAME IN BOTH PROGRAMS \n- For threading, it is necessary to define the operation as Cycle \n- After FEEDRAT command there must be no RAPTO command \n- No defining lines or points \n- No move to point, line or surface command \n- No macro routines \n- No defining variables \n- No program branching \n- No logical conditions ",
    "Nije predana datoteka."    : "No file provided.",
    "Nepostojeća datoteka."     : "File does not exist.",
    "Neispravna vrsta"          : "Invalid file type (must be .txt).",
    "Datoteka učitana:"         : "- File loaded:",
    "Učitavanje linija"         : "- Loading lines",
    "error"                     : "Error while reading file: ",
    "Gotovo."                   : "- Done.",
    "Nepoznata naredba"         : "Error - check the command (not in any of the command categories): ",
    "catia komentari"           : "- Do you want to keep comments from the CATIA APT file? (YES/NO): ",
    "kriv odabir da/ne"         : "- Invalid choice. Please enter again (YES/NO).",
    "cta crc cent nije isti"    : "Error - centers do not match: ",
    "sredina na tang"           : "Error - center of arc on tangent: ",
    "nepoznata ravnina"         : "Error - plane not properly remembered (G17, G18 or G19): ",
    "promjena 3x koord"         : "Error - change of 3 coordinates in one line: ",
    "nepoznat posmak"           : "- Check the type of feedrate (sfm or rpm): ",
    "coolant on off flood mist" : "- Check next line and enter a value (ON/OFF/FLOOD/MIST): ",
    "coolant on off"            : "- Check next line and enter a value (ON/OFF): ",
    "spindle m3/m4"             : "- Check and enter the value of spindle rotation direction (CCLW/CLW/OFF): ",
    "holder type"               : "- Type of tool holder: moving (Enter 0) or fixed (Enter 1): ",
    "nepoznat posmak"           : "- Check the type of feedrate (RPM or SFM): ",
    ";Krivi broj"               : "- Wrong number...",
    "feedrat err"               : "- Check and enter the correct feedrate value (should be MMPR or MMPM): ",
    "posmak"                    : "- Enter RPM or SFM: ",
    "circle feed"               : "- Enter the feedrate for circular motions for rough and finish machining (feedrate type): ",
    "magazine slot"             : "Magazine slot number ",
    "insert r"                  : "Insert radius: ",
    "spindle start"             : "- When starting spindle from M05 to M03/M04, is it needed to reprint the rpm value / cutting speed and rotation direction? (YES/NO): ",
    "krivi spindle start"       : "- Invalid choice, please enter again",
    "ls-clnt"                   : "- Odabrite način podmazivanja (FLOOD/MIST): ",
    "neispravan godlta"         : "Error - invalid golta value: ",
    "intol"                     : ";Inside path tolerance: ",
    "outtol"                    : ";Outside path tolerance: ",
    "toler"                     : ";Path tolerance: ",
    "Nema ciklusa"              : "Error - no cycle defined: ",
    "unijeti ravninu - kruznica": "- Error - plane for circular motion not defined. Enter (G17, G18 or G19): ",
    "units"                     : "- Enter measurement unit (INCH/MM)",
    "neispravni podaci"         : "Error - invalid data for this command:",
    "spremljeno u"              : "File has been translated and saved in: ",
    "partno"                    : ";Part: ",
    "unesite datoteku"          : "- Enter the file name (with .txt extension): ",
    "tlaxis"                    : "; The following values are possible vector directions of the cutting tool:",
    "neobradeni cycle"          : "Error - unprocessed Cycle command: ",
    "pokretanje"                : "Starting Post Processor...\n",
    "naziv output fl"           : "Enter the name of the output file: ",
    "ekstenzija output"         : "Enter the extension of the output file (press ENTER for .txt): ",
    "save file y/n"             : "Do you want to create an output file? (YES/NO): ",
    "neispravni naziv"          : "Error - invalid file name.",
    "kraj"                      : "End of program.",
    "ne zeli spremiti"          : "G-code is printed in the terminal."
    
}
